### PR TITLE
Create Chapter 11 Alternative Method

### PR DESCRIPTION
**Pull request by pettypychen**
Chapter 11 Alternative Method of Calculating the Expected Value of Y When A = 90.

### CODE REVIEW

**Comment by jrfiedler** [comment]
So it looks like these lines
```
# Alternative method of calculating the expected value of Y when A =90
# .get_prediction is an easier way of calculating the expected value and 95% CI
pred = res.get_prediction(exog=[1,90])
# Will generate error message, but used to call out the data in a dataframe     
pred.summary_frame()
```
would replace cells 15 and 16 in the chapter11.ipynb notebook.

This looks good.

Can you put this in the notebook and submit the changed notebook in a pull request? I could do it (and cite this in the commit message), but I think a pull request gives you credit more directly. By the way, I didn't get an error or warning message with the `pred.summary_frame()` line.

**Comment by pettypychen** [comment]
Dear James,

Sorry, I am a GitHub newbie. I don’t know how to put my jupyter notebook in a pull request. I tried googling it, but I didn’t find anything that could help me. Do you think you can guide me through the steps?

Best regards,

Petty

**Comment by jrfiedler** [comment]
Sure, no problem.

I'm assuming you have a local copy of the repo, on your own computer. If not, let me know.

I think the main thing is, in your local copy of the repo, you'll make the changes to the **existing** chapter11.ipynb. (And if you don't get the changes right the first time, for your final version restart the kernel and run all the cells, so that they're numbered sequentially, 1, 2, 3, ...) Then you'll commit those changes, and make the pull request as usual.

Let me know if there are particular steps you get stuck on. I'll be happy to help.

**Comment by pettypychen** [comment]
I managed to put the revision on my GitHub: https://github.com/pettypychen/PullRequest/blob/master/chapter11.ipynb <https://github.com/pettypychen/PullRequest/blob/master/chapter11.ipynb>.

But the pull request showed that there is nothing to compare. I can’t figure out how to get the Jupyter Notebook to show up in the pull request. 

Thank you!

Petty

**Comment by jrfiedler** [comment]
I guess I'm not sure what process you are using, or the process you used to create the first pull request.

Here is how I would create the pull request. I don't know how this fits in with what you're doing already. Possibly you could follow all of these steps, or, if individual steps help, pick and choose.

1. Create a fork of this repo in your GitHub account (using the "Fork" button on the main page of this repo)
2. Clone your forked repo onto your computer.
3. Make changes to the `chapter11.ipynb` in the clone on your computer
4. Commit the changes, and push them to your fork on GitHub
5. Create a pull request from your updated fork to this repo. This page might help: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Pull request closed without merging**
